name = "collabcanvas"
main = "src/worker.ts"
compatibility_date = "2025-10-19"
compatibility_flags = ["nodejs_compat", "enable_ctx_exports"]
workers_dev = false

[[routes]]
pattern = "canvas.adamwhite.work"
custom_domain = true

[assets]
binding = "ASSETS"
directory = "web/dist"

[ai]
binding = "AI"
remote = true

[durable_objects]
bindings = [
  { name = "RoomDO", class_name = "RoomDO" },
  { name = "AIAgent", class_name = "AIAgent" }
]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 0.1
invocation_logs = true

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["AIAgent"]

[vars]
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuYWRhbXdoaXRlLndvcmsk"
