name = "collabcanvas"
main = "src/worker.ts"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "web/dist"

[durable_objects]
bindings = [
  { name = "RoomDO", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_c21pbGluZy1jaGlja2VuLTUyLmNsZXJrLmFjY291bnRzLmRldiQ"

