name = "collabcanvas"
main = "src/worker.ts"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "canvas.adamwhite.work"
custom_domain = true

[assets]
binding = "ASSETS"
directory = "web/dist"

[durable_objects]
bindings = [
  { name = "RoomDO", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[vars]
# TODO: Replace with production Clerk key (pk_live_...) before deploying to production
# Development key is fine for testing, but production should use a live key
CLERK_PUBLISHABLE_KEY = "pk_test_c21pbGluZy1jaGlja2VuLTUyLmNsZXJrLmFjY291bnRzLmRldiQ"
