name = "collabcanvas"
main = "src/worker.ts"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "canvas.adamwhite.work"
custom_domain = true

[assets]
binding = "ASSETS"
directory = "web/dist"

[ai]
binding = "AI"
remote = true

[durable_objects]
bindings = [
  { name = "RoomDO", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[vars]
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuYWRhbXdoaXRlLndvcmsk"

# LangSmith Configuration (for AI observability)
# Set LANGSMITH_API_KEY via: wrangler secret put LANGSMITH_API_KEY
# Set LANGSMITH_PROJECT via: wrangler secret put LANGSMITH_PROJECT
# Optional: LANGSMITH_ENDPOINT (defaults to https://api.smith.langchain.com)
