name = "collabcanvas"
main = "src/worker.ts"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "canvas.adamwhite.work"
custom_domain = true

[assets]
binding = "ASSETS"
directory = "web/dist"

[durable_objects]
bindings = [
  { name = "RoomDO", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[vars]
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuYWRhbXdoaXRlLndvcmsk"
AI_MODEL = "@cf/meta/llama-3.1-8b-instruct"
